const W="https://wa.me/5588981495878?text=Oi%21%20Vim%20pelo%20site%20lojaqp.com.br%20e%20quero%20aproveitar%20a%20promo%C3%A7%C3%A3o.";
const modelos=[
["Nike KD 18","/layout/thumbnails/nikekd18.png"],
["Nike Air Zoom GT Cut 3","/layout/thumbnails/nikeairzoomgtcut3.png"],
["Nike Kyrie 5","/layout/thumbnails/nikekyrie5spongebob.png"],
["Nike Ja 3","/layout/thumbnails/nikeja3.png"],
["Nike Freak 7","/layout/thumbnails/nikefreak7.png"],
["Nike Sabrina 3","/layout/thumbnails/nikesabrina3.png"],
["Puma LaMelo MB.04","/layout/thumbnails/pumalamelomb04.png"],
["Under Armour Curry 8","/layout/thumbnails/underarmourcurry8.png"]
] as const;
const relatos=[
["Chegouuu","Muito obrigado","Ficou muito bom, muito obrigado mesmo"],
["Chegou meu BB 😍","Simplesmente maravilhoso","Já até indiquei a loja de vocês"],
["Chegou!","Qualidade impecável","Muito obg pelo atendimento"],
["Chegou certinho","Muito confortável e lindo!!","Amei ❤️"],
["Chegou minha lindeza 😍","Mais lindo ainda ao vivo 🥹"],
["Chegou","Atendimento top","Muito obrigado pela atenção"]
] as const;
function CTA({children}:{children:React.ReactNode}){return <a className="cta" href={W} target="_blank" rel="noreferrer">{children}</a>}
export default function Home(){return <main>
<div className="top">🔥 ÚLTIMOS DIAS DA PROMOÇÃO 🔥</div>
<header><div className="wrap nav"><a href="#inicio" className="brand"><img src="/layout/logo/logo.png" alt="logo"/><b>lojaqp.com.br</b></a><nav><a href="#modelos">Modelos</a><a href="#clientes">Clientes</a><a href="#envios">Envios</a><a href="#garantia">Garantia</a><a href="#faq">Dúvidas</a></nav><a className="mini" href={W} target="_blank" rel="noreferrer">WhatsApp</a></div></header>
<section id="inicio" className="hero"><div className="wrap heroGrid"><div><p className="eyebrow">OFERTA POR TEMPO LIMITADO</p><h1>Últimos dias <span>para garantir o seu par</span></h1><p className="lead">Tênis de basquete e lifestyle. Veja modelos de referência e consulte disponibilidade, cores e tamanhos direto no atendimento.</p><div className="actions"><CTA>💬 Quero aproveitar no WhatsApp</CTA><a className="ghost" href="#modelos">Ver modelos ↓</a></div><div className="prices"><div><small>1 PAR POR</small><strong>R$299</strong></div><div><small>2 PARES POR</small><strong>R$499</strong></div><div><small>FRETE</small><strong>GRÁTIS</strong></div><div><small>CARTÃO</small><strong>12X S/ JUROS</strong></div></div><p className="note">Pix à vista • Parcelamento somente no cartão • Sem Pix parcelado</p></div><div className="heroCard"><img className="roundLogo" src="/layout/logo/logo.png" alt=""/><img className="shoe" src="/layout/thumbnails/nikekd18.png" alt="Tênis em destaque"/><div className="availability"><b>CONSULTE DISPONIBILIDADE</b><span>Modelos, cores e tamanhos são confirmados pelo atendimento.</span></div></div></div></section>
<section className="trust"><div className="wrap trustGrid"><div>🚚<span><b>Envio pelos Correios</b><small>Todo o Brasil</small></span></div><div>⚡<span><b>Despacho rápido</b><small>Mesmo dia ou dia seguinte</small></span></div><div>🕒<span><b>Prazo médio</b><small>5 dias úteis</small></span></div><div>💳<span><b>Pagamento</b><small>Pix ou até 12x sem juros</small></span></div></div></section>
<section id="modelos" className="section"><div className="wrap"><div className="heading"><p className="eyebrow">MODELOS DE REFERÊNCIA</p><h2>Escolha o estilo. A gente confirma o que está disponível.</h2><p>Não é catálogo de estoque: são referências para você visualizar estilos. Consulte disponibilidade real pelo WhatsApp.</p></div><div className="products">{modelos.map(([n,i])=><a className="product" href={W} target="_blank" rel="noreferrer" key={n}><div className="pic"><img src={i} alt={n}/></div><div className="pinfo"><b>{n}</b><span>Consultar disponibilidade →</span></div></a>)}</div><div className="center"><CTA>Consultar modelos e tamanhos</CTA></div></div></section>
<section id="clientes" className="section dark"><div className="wrap"><div className="heading"><p className="eyebrow">PROVA SOCIAL</p><h2>Clientes recebendo e aprovando</h2><p>Mensagens recebidas depois que os pedidos chegaram.</p></div><div className="feedbacks">{relatos.map((r,idx)=><article className="feedback" key={idx}><div className="fhead"><span>✓</span><div><b>Cliente verificado</b><small>Feedback pelo atendimento</small></div></div><div className="chat">{r.map(m=><p key={m}>{m}</p>)}</div></article>)}</div><p className="caption">Os prints reais enviados serão incorporados na etapa de mídia, mantendo a privacidade dos clientes.</p></div></section>
<section id="envios" className="section"><div className="wrap"><div className="heading"><p className="eyebrow">PEDIDOS EM MOVIMENTO</p><h2>Envios para todo o Brasil</h2><p>O pedido é preparado, conferido e despachado pelos Correios.</p></div><div className="ship"><div><span>📦</span><h3>Pedido preparado</h3><p>Conferência do par, embalagem e separação para postagem.</p></div><div><span>🚚</span><h3>Postagem nos Correios</h3><p>Despachado no mesmo dia ou no dia seguinte, dependendo do horário.</p></div><div><span>🇧🇷</span><h3>Brasil inteiro</h3><p>Frete grátis na promoção e prazo médio informado de 5 dias úteis.</p></div></div><div className="callout"><div><b>FRETE GRÁTIS NA PROMOÇÃO</b><h3>Do atendimento até a postagem sem complicação.</h3><p>Consulte seu tamanho, escolha o modelo disponível e finalize tudo pelo WhatsApp.</p></div><CTA>Quero comprar agora</CTA></div></div></section>
<section id="garantia" className="section dark"><div className="wrap"><div className="heading"><p className="eyebrow">COMPRA COM TRANQUILIDADE</p><h2>💎 Garantia lojaqp.com.br 💎</h2></div><div className="guarantees"><div><span>🛡️</span><h3>Trocas por defeito</h3><p>Sem custo para o cliente.</p></div><div><span>🔁</span><h3>Trocas por numeração</h3><p>Você paga somente o frete para mandar o produto de volta para a loja. O novo tamanho é reenviado sem custo.</p></div><div><span>💎</span><h3>Reembolso garantido</h3><p>Caso não goste do produto, envie o pedido de volta e o reembolso é processado após o retorno do item.</p></div></div></div></section>
<section id="faq" className="section"><div className="wrap narrow"><div className="heading"><p className="eyebrow">DÚVIDAS FREQUENTES</p><h2>Tudo que você precisa saber antes de chamar</h2></div><div className="faqs"><details><summary>Como funciona a promoção?</summary><p>1 par por R$299 ou 2 pares por R$499, com frete grátis para todo o Brasil.</p></details><details><summary>Como vejo modelos e tamanhos?</summary><p>Os modelos são referências. Disponibilidade real é confirmada no WhatsApp.</p></details><details><summary>Quais são as formas de pagamento?</summary><p>Pix à vista ou cartão em até 12x sem juros. Pix parcelado não disponível.</p></details><details><summary>Quando o pedido é enviado?</summary><p>Mesmo dia ou dia seguinte, dependendo do horário. Prazo médio: 5 dias úteis.</p></details><details><summary>Como funciona a garantia?</summary><p>Defeito: troca sem custo. Numeração: você paga o frete de volta e o novo tamanho é reenviado sem custo.</p></details></div></div></section>
<section className="final"><div className="wrap"><p className="eyebrow">ÚLTIMOS DIAS</p><h2>1 par por <span>R$299</span> ou 2 pares por <span>R$499</span></h2><p>Frete grátis • Pix à vista • Cartão em até 12x sem juros</p><CTA>💬 Falar com o atendimento</CTA></div></section>
<footer><div className="wrap foot"><div className="brand"><img src="/layout/logo/logo.png" alt="logo"/><div><b>lojaqp.com.br</b><small>Tênis de basquete e lifestyle</small></div></div><div className="legal"><p><b>CNPJ:</b> 06.847.704/0001-80</p><p><b>Razão Social:</b> Kataia Industria e Comercio de Calcados LTDA</p><p><b>Nome Fantasia:</b> Ceara Calcados</p><p>Operação 100% online • Atendimento via WhatsApp • Envio pelos Correios</p></div><CTA>WhatsApp</CTA></div></footer>
<div className="mobile"><a href={W} target="_blank" rel="noreferrer">💬 Falar no WhatsApp</a></div>
</main>}